version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  # Ignore all tooling (it can get old, it's mature enough)
  - dependency-name: selenium
  - dependency-name: black
  - dependency-name: pylint
  - dependency-name: flake8
  - dependency-name: isort
  - dependency-name: mypy
  - dependency-name: flynt
  # Ignore all patch updates.
  - dependency-name: '*'
    update-types: ["version-update:semver-patch"]

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
