---

# Run this whenever you want the latest code pulled and loaded.

- hosts: all
  tasks:
  - include_vars: defaults.yml
  - name: git pull
    become: yes
    become_user: www-data
    git:
      repo=https://github.com/freelawproject/courtlistener.git
      dest={{ install_root }}
      clone=no
  - name: update python dependencies
    become: yes
    become_user: root
    pip:
      virtualenv={{ virtualenv_root }}
      requirements={{ install_root }}/requirements.txt
    tags:
     - dependencies
  - name: update seals
    become: yes
    become_user: "{{ web_user }}"
    command: "{{ virtualenv_root }}/bin/update-seals"

- hosts: web
  tasks:
  - include_vars: defaults.yml
  - name: collectstatic
    become: yes
    become_user: "{{ web_user }}"
    django_manage:
      app_path={{ install_root }}
      command=collectstatic
      virtualenv={{ virtualenv_root }}
  - name: touch apache
    become: yes
    become_user: "{{ web_user }}"
    file:
      path={{ install_root }}/apache/django.wsgi
      state=touch

- hosts: db, dev
  tasks:
  - include_vars: defaults.yml
  - name: migrate database
    django_manage:
      app_path={{ install_root }}
      command=migrate
      virtualenv={{ virtualenv_root }}

- hosts: celery
  tasks:
  - name: restart celeryd
    become: yes
    become_user: root
    service:
      name=celeryd
      state=restarted
